Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.hostname = "docker"
  config.vm.provision "shell", path: "provision.sh"

  # comandos que não estão no curso
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  
end
